# Generated by Django 2.2.2 on 2021-02-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('phone_number', models.CharField(max_length=15)),
                ('details', models.TextField(max_length=400)),
                ('software_type', models.CharField(choices=[('Web Application', 'Web Application'), ('Mobile Application', 'Mobile Application'), ('Desktop Application', 'Desktop Application'), ('Chatbot', 'Chatbot'), ('Web Crawler', 'Web Crawler'), ('Others', 'Others')], max_length=30)),
                ('category', models.CharField(blank=True, choices=[('Personal Project', 'Personal Project'), ('Business Project', 'Business Project'), ('Academic/School Project', 'Academic/School Project'), ('Research Project', 'Research Project'), ('Others', 'Others')], max_length=70)),
            ],
        ),
    ]
