# Generated by Django 2.2.2 on 2021-02-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
