# Generated by Django 2.2.2 on 2021-02-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_customer_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='details',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
